.gitattributes
Fixes for line endings binary files are marked to be skipped
=> fix(line): Fixes for line endings

zbpod/lang/english/dialogs.tra, zbpod/zbpod.tp2
Add the introductions to the tra so they can be refered to in BAF files.
=> feat(introductions): Add introductions and autotra to tp2 file

zbpod/cutscene/ohbcut00.baf, zbpod/lang/english/dialogs.tra, zbpod/lang/english/weidu.tra, zbpod/test/about this folder.txt, zbpod/test/zbvci.d, zbpod/zbpod.tp2
- Added two globals to cutscene file. One that skips Bello's intro dialogue, and one that to check that we're playing PoD (for interjects). 
- Made some tra edits both in the dialogs and weidu file (for the new tp2 options).
- Added some lines to the tp2 to install my test components (dialogues). 
- Started writing some BASIC vanilla npc interjections, still not proofread or approved, thus not tra-ified and added to the dialogs.tra file.
=> Further Dialogue Edits

ref/baf/oh8000.baf
=> feat(oh8000): Add oh8000.baf

zbpod/zbpod.tp2
- Sweeping a few older coding things under the rug - since we don't use them anymore.
- Edited tp2 to remove install of said files.
- I DON'T have permission to delete the old files from github directly. So, if possible, I need Zen or Royal to delete the 'tpa' folder from the 'test' folder along with the 'podthay' and 'podtrades' files in the main test folder.
=> Code cleanup

zbpod/bp2scripts/ohbhub.baf
=> fix(rep): Remove rep set

zbpod/bp2scripts/ohbhub.baf, zbpod/dlg/ohbdenna.d
=> feat(arena): Better arena rewards

zbpod/bp2scripts/ohbhub.baf
=> fix(arena): Reward exp fixed, sorry @zenblack

zbpod/zbpod.tp2
=> feat(alt): add alt portrait folder

zbpod/bp2scripts/zbtrain.baf, zbpod/cutscene/zbtrain4.baf, zbpod/cutscene/zbtrain5.baf, zbpod/dlg/ohbstirv.d
=> feat(fights): More creature fights

zbpod/bp2scripts/zbtrain.baf, zbpod/cutscene/zbtrain0.baf
=> feat(cheer): Add cheer

zbpod/readme.html
=> chore: Add Microsoft Designer

zbpod/zbpod.tp2
=> fix: Subcomponent

zbpod/cutscene/zbmescut.baf, zbpod/cutscene/zbnephsk.baf
=> fix: Dispell after cutscene

zbpod/dlg/ohbtartl.d, zbpod/lang/english/dialogs.tra
=> feat(once): Only fight once no backies, closes #65

zbpod/lang/english/game.tra, zbpod/lib/fragments/setup_items.tph
=> feat(bg1items): Import bg1 items with tra,  #86

zbpod/lib/fragments/setup_items.tph
typo in blazing bull spell edit
=> install error fix

zbpod/nephetel/core.tpa
=> fix(messanger): Fix for messanger so she can talk

zbpod/zbpod.tp2
=> fix(stores): Fix stores

zbpod/lib/fragments/setup_cre.tph
- Adds x2 skull traps and x2 delayed blast fireballs to the drow mage. The existing mage scripts will cast these two spells.
=> More Offensive Drow Mage

zbpod/cutscene/zbcut00s.baf, zbpod/cutscene/zbcut02s.baf, zbpod/cutscene/zbcut06s.baf, zbpod/cutscene/zbcut07s.baf
=> fix: Interjection bug

zbpod/bp2scripts/ohbhub.baf, zbpod/cutscene/ohbcut07.baf
=> fix(neph): Better posistion for neph

zbpod/cutscene/ohbcut07.baf, zbpod/lang/english/cutscenes.tra
=> feat(neph): Neph feast interject

zbpod/cutscene/ohbcut07.baf, zbpod/lang/english/cutscenes.tra
=> fix(string): Update tra file and longer wait

zbpod/creatures/#scripts/modruid1.baf, zbpod/creatures/#scripts/momage1.baf, zbpod/creatures/#scripts/momatk01.baf, zbpod/creatures/#scripts/mopries1.baf, zbpod/creatures/#scripts/moratk01.baf, zbpod/creatures/#scripts/motatk01.baf, zbpod/lib/fragments/setup_cre.tph
- Updated buffs to be instant w/ 2 buffs occurring at the beginning of the fight
- mages now have buffs
- removed delay at beginning of combat
=> update buffs and prep

zbpod/cutscene/zbmescut.baf, zbpod/lang/english/cutscenes.tra, zbpod/lang/english/game.tra
=> feat(update): Update Dialogue

zbpod/cutscene/zbmescut.baf, zbpod/lang/english/cutscenes.tra, zbpod/nephetel/core.tpa, zbpod/zbpod.tp2
=> fix(traification): Add a fix for traification

zbpod/cutscene/zbmescut.baf
=> fix(wait): Longer jam wait

zbpod/nephetel/dlg/zbneph.d
=> fix(nephInterject): Fixed into dialogue

zbpod/bp2scripts/ohbhub.baf, zbpod/nephetel/dlg/zbneph.d
=> fix(neph): Trigger neph script

zbpod/creatures/#scripts/mohunt1.baf, zbpod/lib/fragments/setup_cre.tph
Every man's dream, an angry nymph will now chase after the player.
=> Nymph Hunting

zbpod/creatures/#scripts/momatk01.baf, zbpod/creatures/#scripts/moratk01.baf, zbpod/creatures/#scripts/motatk01.baf
Use AttackReevaluate instead of AttackOneRound
=> Cleanup Attacks

zbpod/dlg/ohbtartl.d, zbpod/nephetel/core.tpa, zbpod/nephetel/dlg/zbnephj.d, zbpod/zbpod.tp2
=> fix(refer): Fix refer

zbpod/bp2scripts/ohbhub.baf, zbpod/dlg/ohbtartl.d, zbpod/lang/english/neph.tra, zbpod/nephetel/core.tpa, zbpod/nephetel/dlg/zbnephj.d, zbpod/zbpod.tp2
=> fix(interject): More interject fixes

zbpod/dlg/ohbtartl.d
=> feat(tartld): Slightly better tartld dialogue

zbpod/cutscene/zbmescut.baf, zbpod/zbpod.tp2
=> feat(vvcs): Add vvcs to mod

zbpod/lib/fragments/setup_cre.tph
- Remove sunfire from Orc Mage spell list.
=> Orc Mage Spell List

zbpod/bp2scripts/ohbhub.baf
Adds festering maw after tier 1 round of fights is complete.
=> Festering Maw

zbpod/lib/fragments/setup_items.tph
=> fix(item): Fix item copy

zbpod/animations/fallen_planetar/Exxx.INI, zbpod/creatures/#scripts/momatk01.baf, zbpod/creatures/#scripts/moratk01.baf, zbpod/lib/fragments/setup_cre.tph
Update the fallen planetar animation for ohbwing.cre.
=> Fallen Planetar

zbpod/cutscene/zbmescut.baf, zbpod/zbpod.tp2
=> feat(bam): Add bam for vvc

zbpod/lang/english/neph.tra, zbpod/nephetel/dlg/zbnephj.d
=> fix(match5): Fix match 5 dialogue

zbpod/zbpod.tp2
=> fix(stores): Creatures who run stores should be named correctly

zbpod/nephetel/dlg/zbnephp.d
=> fix(kickout): Kickout should use move global

zbpod/lib/fragments/setup_cre.tph
=> Orc Fight DR

zbpod/bp2scripts/ohb_102.baf, zbpod/bp2scripts/ohbhub.baf, zbpod/dlg/ohbbrodl.d, zbpod/dlg/ohbdenna.d
=> fix(revert): Revert script change

zbpod/dlg/zbvci.d, zbpod/zbpod.tp2
=> fix(missing): Add missing strings

zbpod/bp2scripts/ohbhub.baf
=> fix(reset): Do not reset all

zbpod/dlg/zbvci.d
=> feat(training): Add some pre-training match dialogue

zbpod/bp2scripts/ohb_105.baf
=> fix(neph): Make neph ally

zbpod/bp2scripts/ar0406.baf, zbpod/bp2scripts/ohb_105.baf, zbpod/bp2scripts/ohbhub.baf, zbpod/lib/fragments/setup_areas.tph, zbpod/nephetel/baf/zbnephm.baf, zbpod/nephetel/dlg/zbneph.d
=> fix(move): Fix move neph to copper cornet

zbpod/bp2scripts/ohb_105.baf, zbpod/bp2scripts/ohbhub.baf, zbpod/cutscene/zbtrain0.baf, zbpod/dlg/ohbstirv.d, zbpod/lang/english/dialogs.tra
=> feat(striv): Updates for striv, Closes #230

zbpod/lang/english/game.tra, zbpod/lang/english/neph.tra, zbpod/nephetel/dlg/zbmes.d
Brought Nephetel's messenger dialogue and Gaelan's document up to scratch with gdocs.
=> Messenger updates

zbpod/nephetel/core.tpa
=> fix(selection): Fix selection sounds

.github/scripts/check.sh, .github/workflows/checks.yaml, zbpod/cutscene/ohbcut00.baf, zbpod/dlg/ohbjoker.d, zbpod/lang/english/cutscenes.tra, zbpod/lang/english/dialogs.tra
=> fix(cutscene): Fix cutscene to be inline with @llewren changes

zbpod/dlg/ohbstirv.d, zbpod/dlg/zbvci.d, zbpod/lang/english/dialogs.tra
=> fix(striv): Fix for striv interjections use latest @llewren dialogue

zbpod/dlg/zbvci.d, zbpod/lang/english/dialogs.tra, zbpod/nephetel/dlg/zbinterj.d, zbpod/nephetel/dlg/zbneph.d, zbpod/nephetel/neph.tpa
=> feat(voghiln): Voghiln interjections for new dialogue

zbpod/lib/fragments/setup_items.tph, zbpod/nephetel/dlg/zbneph.d, zbpod/nephetel/neph.tpa
=> fix(dialogue): Fix dialogue bug with neph
